# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e41b2ca948370a3f361b11ae228a3f71ba4f441e9eda12679e88e1df948e0044928dd1baaa8aca05fedb94c2770817559e6437a7f1ec780c784f091eab2c37d8

test:
  secret_key_base: 244907df2a8768138fc52e33e5b1665e02ab2fc98817f94dda0ed06998e30a864fb5ccc5c4ae97c58941d898f6414126a7724cdecc0c87ed3c66a55e0eea696a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
